openapi: 3.0.0
info:
  title: Navigation API
  description: API for managing navigation menu items
  version: 1.0.0
servers:
  - url: /api
    description: Development server

paths:
  /navigation:
    get:
      summary: Get navigation menu items
      description: Retrieve all navigation items organized by category
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/NavigationItem'
                  categories:
                    type: array
                    items:
                      $ref: '#/components/schemas/NavigationCategory'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    NavigationItem:
      type: object
      required:
        - id
        - label
        - href
        - category
        - order
        - isActive
        - isVisible
      properties:
        id:
          type: string
          description: Unique identifier for the navigation item
        label:
          type: string
          description: Display text for the navigation item
          maxLength: 50
        href:
          type: string
          description: URL path for the navigation item
          pattern: '^/[a-zA-Z0-9/-]*$'
        category:
          $ref: '#/components/schemas/NavigationCategory'
        order:
          type: integer
          description: Display order within category
          minimum: 1
          maximum: 7
        isActive:
          type: boolean
          description: Current page indicator
        isVisible:
          type: boolean
          description: Show/hide in navigation

    NavigationCategory:
      type: object
      enum:
        - main
        - company
        - services
        - work
        - resources

    Error:
      type: object
      required:
        - message
        - code
      properties:
        message:
          type: string
          description: Error message
        code:
          type: string
          description: Error code
        details:
          type: object
          description: Additional error details
