openapi: 3.0.0
info:
  title: Testimonials API
  description: API for managing client testimonials in footer
  version: 1.0.0
servers:
  - url: /api
    description: Development server

paths:
  /testimonials:
    get:
      summary: Get client testimonials
      description: Retrieve all visible testimonials for footer display
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  testimonials:
                    type: array
                    items:
                      $ref: '#/components/schemas/Testimonial'
                  total:
                    type: integer
                    description: Total number of testimonials
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Testimonial:
      type: object
      required:
        - id
        - quote
        - author
        - title
        - company
        - isVisible
        - order
      properties:
        id:
          type: string
          description: Unique identifier for the testimonial
        quote:
          type: string
          description: Client testimonial text
          maxLength: 200
        author:
          type: string
          description: Client name
          maxLength: 50
        title:
          type: string
          description: Client job title
          maxLength: 50
        company:
          type: string
          description: Client company name
          maxLength: 50
        isVisible:
          type: boolean
          description: Show/hide in footer
        order:
          type: integer
          description: Display order in testimonials section
          minimum: 1

    Error:
      type: object
      required:
        - message
        - code
      properties:
        message:
          type: string
          description: Error message
        code:
          type: string
          description: Error code
        details:
          type: object
          description: Additional error details
