openapi: 3.0.0
info:
  title: Web Scraping API
  description: API for scraping AI news content using Firecrawl MCP
  version: 1.0.0
servers:
  - url: /api
    description: Development server

paths:
  /scrape/ai-news:
    post:
      summary: Scrape latest AI news articles
      description: Use Firecrawl MCP to scrape 5-8 latest AI news articles from various sources
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sources:
                  type: array
                  items:
                    type: string
                  description: List of AI news sources to scrape
                  example: ["https://openai.com/blog", "https://anthropic.com/news", "https://deepmind.com/blog"]
                maxArticles:
                  type: integer
                  minimum: 5
                  maximum: 8
                  default: 6
                  description: Maximum number of articles to scrape
                categories:
                  type: array
                  items:
                    $ref: '#/components/schemas/NewsCategory'
                  description: AI news categories to focus on
      responses:
        '200':
          description: Successful scraping response
          content:
            application/json:
              schema:
                type: object
                properties:
                  articles:
                    type: array
                    items:
                      $ref: '#/components/schemas/ScrapedArticle'
                  totalScraped:
                    type: integer
                    description: Number of articles successfully scraped
                  sourcesUsed:
                    type: array
                    items:
                      type: string
                    description: Sources that were successfully scraped
                  scrapingTime:
                    type: string
                    description: Time taken to complete scraping
        '400':
          description: Bad request - invalid scraping parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error during scraping
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /scrape/refresh:
    post:
      summary: Refresh AI news content
      description: Trigger a refresh of AI news content from all configured sources
      responses:
        '200':
          description: Successful refresh
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "AI news content refreshed successfully"
                  articlesUpdated:
                    type: integer
                    description: Number of articles updated
                  newArticles:
                    type: integer
                    description: Number of new articles added
        '500':
          description: Internal server error during refresh
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    ScrapedArticle:
      type: object
      required:
        - title
        - excerpt
        - content
        - sourceUrl
        - date
        - category
      properties:
        title:
          type: string
          description: Article headline
          maxLength: 100
        excerpt:
          type: string
          description: Article summary
          maxLength: 300
        content:
          type: string
          description: Full article content
        sourceUrl:
          type: string
          format: uri
          description: Original article URL
        date:
          type: string
          format: date-time
          description: Publication date
        category:
          $ref: '#/components/schemas/NewsCategory'
        tags:
          type: array
          items:
            type: string
          maxItems: 5
          description: Article tags for filtering
        imageUrl:
          type: string
          format: uri
          description: Article featured image URL
        readTime:
          type: string
          description: Estimated reading time
          pattern: '^\\d+\\s+min\\s+read$'

    NewsCategory:
      type: string
      enum:
        - AI Models
        - Biotech AI
        - AI Safety
        - Enterprise AI
        - Research
        - Autonomous Vehicles

    Error:
      type: object
      required:
        - message
        - code
      properties:
        message:
          type: string
          description: Error message
        code:
          type: string
          description: Error code
        details:
          type: object
          description: Additional error details
