openapi: 3.0.3
info:
  title: Case Studies API
  description: API for managing case studies and project outcomes
  version: 1.0.0
  contact:
    name: BestIT Consulting
    email: contact@bestitconsulting.com

servers:
  - url: https://api.bestitconsulting.com/v1
    description: Production server
  - url: https://staging-api.bestitconsulting.com/v1
    description: Staging server

paths:
  /case-studies:
    get:
      summary: Get all case studies
      description: Retrieve all active case studies with metrics
      tags:
        - Case Studies
      parameters:
        - name: category
          in: query
          schema:
            type: string
          description: Filter by service category
        - name: limit
          in: query
          schema:
            type: integer
            default: 10
          description: Number of case studies to return
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
          description: Number of case studies to skip
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/CaseStudy'
                  meta:
                    type: object
                    properties:
                      total:
                        type: integer
                        example: 3
                      page:
                        type: integer
                        example: 1
                      limit:
                        type: integer
                        example: 10
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /case-studies/{id}:
    get:
      summary: Get case study by ID
      description: Retrieve a specific case study with all metrics
      tags:
        - Case Studies
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Case study ID
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/CaseStudy'
        '404':
          description: Case study not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /case-studies/{id}/metrics:
    get:
      summary: Get metrics for case study
      description: Retrieve all metrics for a specific case study
      tags:
        - Case Studies
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Case study ID
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/CaseStudyMetric'
        '404':
          description: Case study not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    CaseStudy:
      type: object
      required:
        - id
        - title
        - challenge
        - solution
        - result
        - metrics
        - technologies
        - client
        - category
      properties:
        id:
          type: string
          example: 'ai-textile-design'
        title:
          type: string
          example: 'AI-Powered Transformation in Textile Design'
        challenge:
          type: string
          example: 'Traditional design process took 12 weeks with low creativity and acceptance rates'
        solution:
          type: string
          example: 'Implemented AI-assisted design system with creative style exploration'
        result:
          type: string
          example: 'Reduced design cycle from 12 weeks to 4-6 days, boosted creativity by 10x, increased acceptance rate to 90%'
        metrics:
          type: array
          items:
            $ref: '#/components/schemas/CaseStudyMetric'
        technologies:
          type: array
          items:
            type: string
          example: ['AI/ML', 'Python', 'TensorFlow', 'Computer Vision']
        client:
          type: string
          example: 'Textile Manufacturing Company'
        duration:
          type: string
          example: '6 months'
        teamSize:
          type: number
          example: 4
        image:
          type: string
          format: uri
          example: '/images/case-studies/ai-textile-design.jpg'
        testimonial:
          type: string
          example: 'AI-assisted design completely changed our process and boosted our creativity by 10x'
        category:
          type: string
          example: 'AI & Machine Learning Solutions'

    CaseStudyMetric:
      type: object
      required:
        - id
        - name
        - value
        - unit
        - improvement
        - type
      properties:
        id:
          type: string
          example: 'design-cycle-reduction'
        name:
          type: string
          example: 'Design Cycle Time'
        value:
          type: string
          example: '4-6 days'
        unit:
          type: string
          example: 'days'
        improvement:
          type: string
          example: 'Reduced from 12 weeks to 4-6 days'
        type:
          type: string
          enum: ['performance', 'cost', 'efficiency', 'quality']
          example: 'efficiency'

    Error:
      type: object
      required:
        - success
        - message
      properties:
        success:
          type: boolean
          example: false
        message:
          type: string
          example: 'Case study not found'
        code:
          type: string
          example: 'CASE_STUDY_NOT_FOUND'
        details:
          type: object
          description: Additional error details

tags:
  - name: Case Studies
    description: Case study and project outcome management
